TimeSheet/Attendance/urls.py
from django.urls import path
from Attendance import views

urlpatterns = [
    path('Details', views.attendance, name='attendance'),
    path('Details/<attendance_id>', views.attendance_Details, name='a_details1'),
    path('DetailsId', views.attendance_Details, name='a_details'),
    path('Attendance', views.make_attendance, name='makeattendance'),
    path('Leaves',views.getleave, name='leave'),
    path('RequestLeave', views.request_leave, name='requestLeave'),
    path('GetAttendance',views.getAttendance, name='getattendance'),
    path('getLeaves',views.getLeave,name='getLeave'),
    path('checkLeave',views.checkLeave,name="checkLeave"),
    
    path('getLeaveDetails/<leave_id>',views.getLeaveDetails,name='getLeaveDetails'),
    
    path('LeaveDetails',views.LeaveDetails,name='LeaveDetails'),
    path('updateLeave',views.updateLeave,name='updateLeave'),
    path('leaveCount',views.getLeaveCount, name='getLeaveCount'),
    path('attendanceCount',views.getattendanceCount, name='getAttendanceCount'),
    
    path('updateLeaveType',views.updateLeaveType, name="updateType"),
    path('getLeaveType',views.getLeaveType,name="getType"),
    path('getToday',views.getTodayAttendance,name='get_todays_attendance'),
    path('getTodayAll',views.getTodayAll,name="getTodaysAllAttendance"),
]

TimeSheet/Issue/urls.py
from django.urls import path
from . import views




urlpatterns= [
 
    path('', views.index, name='index'),
    path('add', views.ADD, name = 'add' ),
    path('details/<issueid>',views.getIssue,name='issueDetails'),
    path('edit', views.EDIT, name ='edit'),
    path('update/<str:id>', views.Update, name= 'Update'),
    path('delete/<id>', views.DELETE, name = 'delete'),
    path('donestatus ', views.Done, name='done'),
    path('updateStatus',views.updateStatus,name='updateTicketStatus'),
    path('addDetails', views.addComments, name= 'addComments'),
    path('gettask',views.getMyTask, name='getmytask'),
   
]

TimeSheet/TimeSheet/urls.py
from django.contrib import admin
from django.urls import path, include

from TimeSheet import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('login', views.login, name='login2'),
    path('activity',views.myActivity,name='getmyactivity'),
    path('test', views.test, name='test'),
    path('validate/', include('Authentication.urls')),
    path('Attendance/', include('Attendance.urls')),
    path('Manage/',include('Manager.urls')),
    path('Project/',include('Project.urls')),
    path('Worklog/',include('emp_worklog.urls')),
    path('Issue/',include('Issue.urls')),
    path('Customer/',include('Customer.urls'))
    
    
]

TimeSheet/Attendance/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Attendance(models.Model):
    date = models.DateField(auto_now_add=True,null=True)
    day = models.CharField(max_length=50,null=True)
    user = models.ForeignKey(User, null=True, on_delete= models.SET_NULL)
    entry = models.CharField(max_length=50)
    lbreak1 = models.CharField(max_length=50,null=True)
    lbreak2 = models.CharField(max_length=50,null=True)
    exit = models.CharField(max_length=50, null=True)
    hour = models.CharField(max_length=50, null=True)
    type = models.CharField(max_length=50,null=True,default=None)
    start_location = models.CharField(max_length=500, null=True)
    stop_location = models.CharField(max_length=500, null=True)

class LeaveType(models.Model):
    name = models.CharField(max_length=50,null=True,default=None)
    days = models.IntegerField(null=True,)

    def __str__(self):
      return self.name

class Approval(models.Model):
    name =models.CharField(max_length=50)
    def __str__(self):
      return self.name

class Leave(models.Model):
    date =  models.DateField(auto_now_add=True,null=True)
    user = models.ForeignKey(User, null=True, on_delete= models.SET_NULL)
    type =  models.ForeignKey(LeaveType,on_delete= models.CASCADE)
    leave_from = models.DateField(null=True)
    leave_to = models.DateField(null=True)
    details = models.TextField()
    approval = models.ForeignKey(Approval, on_delete=models.CASCADE, null=True,default=2)
    approved_by = models.CharField(max_length=50,null=True)
    date_approved = models.DateTimeField(null=True,default=None)

class TrackAttendance(models.Model):
    user = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    btn1 = models.BooleanField(null=True)
    btn2 = models.BooleanField(null=True)
    btn3 = models.BooleanField(null=True)

TimeSheet/Attendance/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpResponseRedirect, HttpResponse
from Attendance.models import Attendance, Leave, LeaveType,User,TrackAttendance
from Authentication.models import userDetails,Company,Employees
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import datetime
from geopy.geocoders import Nominatim
from django.db.models import Sum,Q
from math import radians, cos, sin, asin, sqrt
from Manager.views import checkTeams
#for email send
from django.core.mail import send_mail
from django.conf import settings
# email

# new add
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def attendance(request):
    if request.user.is_authenticated:
        #comp = request.session['comp']
        #user = Employees.objects.filter(company=comp).values('user')
        #allusers =User.objects.filter(pk__in=user).values('id','username')

        getTeam_users = checkTeams(request)
        allusers = User.objects.filter(pk__in=getTeam_users[0])

        #btnTrack=TrackAttendance.objects.get(user=request.user)
        attenType = userDetails.objects.get(user=request.user)
        #print(attenType.attendanceType)
        #send_mail('A cool subject', 'A stunning message', settings.EMAIL_HOST_USER, ['anilrajbanshi31@gmail.com'])
        #getDistance(request) #distance calculator
        date = datetime.date.today()
        if request.user.is_superuser:
            result = Attendance.objects.filter(date__year=date.year,date__month =date.month,user=request.user) # 1=january
        else:
            result = Attendance.objects.filter(date__year=date.year,date__month =date.month, user=request.user)
        #print(result)
        gettoday = Attendance.objects.filter(user=request.user,date=date)
        #print(gettoday.first())
        if gettoday.first() != None:
            today = gettoday.first()
        else :
            today = "None"
        data = {
            'result': result,
            'users' :allusers,
            #'btn' :btnTrack,
            'attendanceType':attenType,
            'today':today
        }
        return render(request, 'Attendance/attendance.html',data)
    else:
        return HttpResponseRedirect(reverse('login'))

def getTodayAttendance(request):
    data = Attendance.objects.filter(date=datetime.date.today(),user=request.user).values()
    return JsonResponse({'result':list(data)})

def getTodayAll(request):
    data = Attendance.objects.filter(date=datetime.date.today()).values()
    return JsonResponse({'result':list(data)})

@csrf_exempt
def getAttendance(request):
    month = request.POST['month']
    year = request.POST['year']
    user_id =request.POST.get('user')
    #print(user_id)
    if user_id == '0':
        result = Attendance.objects.filter(date__month=month,date__year=year)
    elif user_id == None:
        result = Attendance.objects.filter(date__month=month,date__year=year,user=request.user)
    else:
        result = Attendance.objects.filter(date__month=month,date__year=year,user=user_id)

    alldata = getUsernames(request,result)
    return JsonResponse({'attendance':alldata})

#def attendance_Details(request,attendance_id):
def attendance_Details(request):
    attendance_id=request.POST.get('id')
    attendance = Attendance.objects.get(id=attendance_id)
    if attendance.start_location != '':
        start_location = getLocation_Name(attendance.start_location)
    else:
        start_location="Location Not Saved"
    if attendance.stop_location != '':
        stop_location = getLocation_Name(attendance.stop_location)
    else:
        stop_location="Location Not Saved"
    new_data = Attendance()
    new_data.date=attendance.date
    new_data.day=attendance.day
    new_data.entry=attendance.entry
    new_data.lbreak1 =attendance.lbreak1
    new_data.lbreak2 = attendance.lbreak2
    new_data.exit = attendance.exit
    new_data.start_location =start_location
    new_data.stop_location=stop_location

    #return render(request,'Attendance/attendance_details.html',{'data':new_data})
    return JsonResponse({'start':str(new_data.start_location),'stop':str(new_data.stop_location)})

@csrf_exempt
def make_attendance(request):
    btn = request.POST['btn']
    date = request.POST.get('date')
    check_date = Attendance.objects.filter(date=date,user=request.user).exists()
    day = request.POST.get('day')
    entry = request.POST.get('entry')
    lbreak1 = request.POST.get('lbreak1')
    lbreak2 = request.POST.get('lbreak2')
    exit = request.POST.get('exit')
    hour = request.POST.get('hour')
    start_location = request.POST.get('start_location')
    stop_location = request.POST.get('stop_location')
    if check_date == True:
        g_data = Attendance.objects.get(date=date, user=request.user)
        if lbreak1 != None:
            Attendance.objects.filter(id=g_data.id).update(lbreak1 = lbreak1)
            TrackAttendance.objects.filter(user=request.user).update(btn2=True)
        if lbreak2 != None:
            Attendance.objects.filter(id=g_data.id).update(lbreak2 = lbreak2)
            TrackAttendance.objects.filter(user=request.user).update(btn2=False)
        if exit != None:
            #attendance = Attendance(id=g_data.id,user=g_data.user,date=g_data.date,day=g_data.day,entry=g_data.entry,lbreak1=g_data.lbreak1,lbreak2=g_data.lbreak2,exit=exit,hour=hour,start_location=g_data.start_location,stop_location=stop_location)
            Attendance.objects.filter(id=g_data.id).update(exit = exit,hour=hour, stop_location =stop_location)
            TrackAttendance.objects.filter(user=request.user).update(btn3=True,btn1=False)
        #attendance.save()
    else:
        attendance = Attendance(user=request.user,day=day,entry=entry,start_location=start_location)
        TrackAttendance.objects.filter(user=request.user).update(btn1=True,btn3=False)
        attendance.save()

    check_date = datetime.date.today()
    if request.user.is_superuser:
        getAll=Attendance.objects.filter(date__year=check_date.year,date__month=check_date.month,user=request.user)
        alldata = getUsernames(request,getAll)
    else:
        getAll=Attendance.objects.filter(date__year=check_date.year,date__month=check_date.month,user=request.user).values()
        alldata=list(getAll)

    return JsonResponse({'attendance':alldata})

def getUsernames(request,result):
    if request.user.is_superuser:
        #print(result)
        alldata =[]
        for x in result:
            alldata.append({
                'id':x.id,
                'date':x.date,
                'day':x.day,
                'user':x.user.username,
                'entry':x.entry,
                'lbreak1':x.lbreak1,
                'lbreak2':x.lbreak2,
                'exit':x.exit,
                'hour':x.hour
            })
    else:
        alldata = list(result.values())

    return alldata

@login_required
@csrf_exempt
def checkLeave(request):
    d_date = datetime.datetime.now()
    id=request.POST.get('id')
    count = LeaveType.objects.get(id=id)
    leave = Leave.objects.filter(type=count,date__year=d_date.year,date__month=d_date.month,user=request.user)
    print(leave.count())
    return JsonResponse({'available':count.days,'taken':leave.count()})

@login_required
def getleave(request):
    #all_leaves = Leave.objects.all()
    usr = checkTeams(request)
    allusers =User.objects.filter(pk__in=usr[0]).values('id','username')
    all_leaves = Leave.objects.filter(user__id__in=usr[0])

    type = LeaveType.objects.all().values()
    return render(request, 'Attendance/leave.html',{'result':all_leaves,'users' :allusers,'LeaveTypes':type})

def request_leave(request):
    type= request.POST['type']
    leave_from = request.POST['leave_from']
    leave_to = request.POST['leave_to']
    details = request.POST['details']
    leaveType = LeaveType.objects.get(id=type)
    id = request.POST['id']
    if id != "":
        Leave.objects.filter(id=id).update(user = request.user,type=leaveType,leave_from=leave_from,leave_to=leave_to,details=details)
    else:
        Leave(user = request.user,type=leaveType,leave_from=leave_from,leave_to=leave_to,details=details).save()

    if request.user.is_superuser:
        result = Leave.objects.all()
    else:
        result = Leave.objects.filter(user=request.user)

    getmanager = userDetails.objects.get(user__id=request.user.id)
    if getmanager.is_manager == True or request.user.is_superuser:
        manager = True
    else:
        manager = False
    list_data = []
    for x in result:
        list_data.append({
            'date':x.date,
            'user':x.user.username,
            'type':x.type.name,
            'leave_from':x.leave_from,
            'leave_to':x.leave_to,
            'details':x.details,
            'approval':x.approval.name
        })
    #data = list(result)
    #print(list_data)
    return JsonResponse({'result':list_data,'is_manager':manager})

def getLocation_Name(user_location):
    if user_location != None:
        geolocator = Nominatim(user_agent="Timesheet")
        new_location = user_location.split(",")
        Latitude = new_location[0]
        Longitude = new_location[1]
        location = geolocator.reverse(Latitude+","+Longitude)
        address = location.raw['address']
        city = address.get('city', '')
        street = address.get('street_name','')
        state = address.get('state', '')
        country = address.get('country', '')
        code = address.get('country_code')
        zipcode = address.get('postcode')
        #print(location)
        return location
    else:
        return 'Location Disabled'
@login_required
@csrf_exempt
def getLeave(request):
    status = request.POST.get('status')
    user_id = request.POST.get('user')
    usr = checkTeams(request)
    print(user_id)
    if user_id == '0':
        if status == '0':
            result = Leave.objects.filter(user__id__in=usr[0])

TimeSheet/Attendance/templates/Attendance/attendance_details.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
    <form class="container-fluid"> 
      <h4>User Entry Details</h4>
      <div class="row">
        <div class="col-4">
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Date</label>
            <div class="col-sm-6">
              <p>:  {{data.date}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Day</label>
            <div class="col-sm-6">
              <p>:  {{data.day}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Entry</label>
            <div class="col-sm-6">
              <p>:  {{data.entry}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Lunch Break Start</label>
            <div class="col-sm-6">
              <p>:  {{data.lbreak1}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Lunch Break End</label>
            <div class="col-sm-6">
              <p>:  {{data.lbreak2}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Exit</label>
            <div class="col-sm-6">
              <p>:  {{data.exit}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Worked Hour</label>
            <div class="col-sm-6">
              <p>:  {{data.hour}}</p>
            </div>
          </div>
        </div>
        <div class='col-8' >
          <div class="form-group row">
            <label for="date" class="col-sm-3 col-form-label">Logged In Location</label>
            <div class="col-sm-9">
              <p>:  {{data.start_location}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-3 col-form-label">Logged Out Location</label>
            <div class="col-sm-9">
              <p>:  {{data.stop_location}}</p>
            </div>
          </div>
        </div>
      </div>
      <a class="btn btn-sm btn-success" href="{% url 'attendance'%}" id="a_details">See All</a>
      </form>
</div>


{% endblock %}

TimeSheet/Attendance/templates/Attendance/leaveDetails.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
    <form class="container-fluid"> 
        <input type='hidden' value='{{leave.id}}' id="leaveId"/>
      <h4>User Entry Details</h4>
      <div class="row">
        <div class="col-6">
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Requested By</label>
            <div class="col-sm-6">
              <p>:  {{leave.user.username}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Requested Date</label>
            <div class="col-sm-6">
              <p>:  {{leave.date}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Leave Type</label>
            <div class="col-sm-6">
              <p>:  {{leave.type.name}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Leave From</label>
            <div class="col-sm-6">
              <p>:  {{leave.leave_from}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Leave To</label>
            <div class="col-sm-6">
              <p>:  {{leave.leave_to}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-6 col-form-label">Details</label>
            <div class="col-sm-6">
              <p>:  {{leave.details}}</p>
            </div>
          </div>
        </div>
        <div class='col-6' >
            <div class="form-group row">
                <label for="date" class="col-sm-3 col-form-label">Approval</label>
                <div class="col-sm-9">
                  <label>:  {{leave.approval.name}}</label>
                </div>
              </div>
              <div class="form-group row">
                <label for="date" class="col-sm-3 col-form-label">Comment</label>
                <div class="col-sm-9">
                  <textarea class="form-control"></textarea>
                </div>
              </div>
        {% if leave.approval.name != 'Pending' %}
          <div class="form-group row">
            <label for="date" class="col-sm-3 col-form-label">Approved By</label>
            <div class="col-sm-9">
              <p>:  {{leave.approved_by}}</p>
            </div>
          </div>
          <div class="form-group row">
            <label for="date" class="col-sm-3 col-form-label">Approved Date</label>
            <div class="col-sm-9">
              <p>: {{leave.date_approved}} </p>
            </div>
          </div>
        {% endif %}
        <label id='s_text'></label>
        {% if leave.approval.name == 'Pending' and perms.Attendance.change_leave %}
        <div id='btn_action' style="text-align:right;">
            <a class="btn btn-sm btn-success" onclick="update_leave(1,{{leave.id}})">Grant Leave</a>
            <a class="btn btn-sm btn-danger" onclick="update_leave(3,{{leave.id}})">Decline</a>
        </div>
        {% endif %}
        </div> 
      </div>
      <a class="btn btn-sm btn-success" href="{% url 'leave' %}">See All</a>
      </form>
</div>

<script>
    function update_leave(status,id)
    {
     //id=$("#leaveId").val();
      data = {'status':status,'leave_id':id};
      //alert(status+':'+id);
      $.ajax({
          url: "{% url 'updateLeave' %}",
          method: "POST",
          data: data,
          success: function(data){
                $("#s_text").html("Success");
                $('#btn_action').hide();
          },
      });
    }
</script>
{% endblock %}